image: ubuntu:22.04


build:
  stage: build
  script:
    - apt update
    - apt install git -y
    - apt install openjdk-17-jdk -y
    - gradle
    - ./gradlew build
  artifacts:
    paths:
      - "spark-forge/build/libs"